### ISSUE TITLE
Maintaining ddpheno

### ISSUE THREAD

**Issue by matentzn** [obophenotype/dicty-phenotype-ontology#1]
Moved from https://github.com/OBOFoundry/OBOFoundry.github.io/issues/918

@pfey03

Ideally you would edit ddpheno only on this repo here! Did you make any changes since Biocuration to ddpheno?

**Comment by pfey03** [comment]
I need to update on our repo as it's grabbed for our database from there. But I can update the obo on this repo as well. Yes, there was at least one small update, I'll check in a while and see if I can update here without problems

**Comment by pfey03** [comment]
I can't find our phenotype ontology in this Repo. looked at all Obo files and it's all our anatomy ontology! 
I did one update in May. Our up to date phenotype ontology is here:
https://github.com/dictyBase/migration-data/blob/master/ontologies/dicty_phenotypes.obo

**Comment by matentzn** [comment]
Ahhh sorry Petra missed this one here :)

https://github.com/obophenotype/dicty-phenotype-ontology/blob/master/src/ontology/ddpheno-edit.owl

We had moved ddpheno to owl! Do you want to continue to edit it in OBO?

**Comment by pfey03** [comment]
@matentzn sorry late response. 
Yes for now and efficiency sake, I still edit obo and update files in our repo. we are not yet using OWL but will once we are fully in new database.  The plan is once we have our long grant application drama over I eventually will have to learn and use Protege.
Do you know how and how often Obofoundry updates ontologies? Just today updated the anatomy ontology to delete some stale xrefs, will see how long it takes to be out there.

**Comment by pfey03** [comment]
@matentzn also, fetch the DDPHENO from Obofoundry again as Sidd just recently added the line: ontology: ddpheno
needed for import in our new database. The date is still the same as ontology itself has not been edited since 30. May.  But please fetch the update here
http://www.obofoundry.org/ontology/ddpheno.html

**Comment by pfey03** [comment]
And let me know how to update DDPHENO here when I make ontology changes.

**Comment by matentzn** [comment]
Maybe it is easier to do it like this:

- I change ddpheno to OBO as the edit format;
- You physically remove the ddpheno from your other repo, and edit it from here instead
- I show you how to run your own releases, so you are not tied to OBO foundry
- When you are ready to transitition from OBO to OWL, you give me a shout and migrate the repo to owl (which is super easy) and I will give you a quick training session on how to evolve it with Protege etc.

What do you think?

> Do you know how and how often Obofoundry updates ontologies?

This is the BBOB jenkins job; I assume it runs over night. Note that many ontologies manage their own release cycle; you could be one of them, or leave things as they are. Up to you.

**Comment by matentzn** [comment]
This is all done, so closing!
